platform :ios, '9.0'
inhibit_all_warnings!
target 'MVPStudy' do
    ####下拉刷新+json转模型####
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'JMRoundedCorner', :git => 'https://github.com/raozhizhen/JMRoundedCorner.git', :tag => '1.9.6'
    pod 'YYWebImage', :git => 'https://github.com/raozhizhen/YYWebImage.git', :tag => '1.0.5'
    pod 'AFNetworking'
    pod 'ReactiveObjC'
    pod 'MBProgressHUD'    
    pod 'TZImagePickerController'
    pod 'Masonry'
    pod 'DZNEmptyDataSet'
    pod 'Bugly'
    ####键盘管理#####
    pod 'IQKeyboardManager'
    ####其他库#####
    pod 'TYPagerController'
    pod 'Reveal-SDK', configurations: ['Debug']
    pod 'AVOSCloud'
    pod 'SDWebImage'
end
